<?php

//libraries_load('wechat');

/**
 * Implements hook_libraries_info().
 */
function wechat_api_libraries_info() {
  return array(
    'wechat' => array(
      'name' => 'Wechat',
      'vendor url' => 'https://github.com/sosyuki/wechat-php-sdk',
      'download url' => 'https://github.com/sosyuki/wechat-php-sdk',
      'version arguments' => array(
        'file' => 'wechat.class.php',
        'pattern' => "/@version\s+([0-9\.]+)/",
        'lines' => 100,
      ),
      'files' => array(
        'php' => array(
          'wechat.class.php',
        ),
      ),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function wechat_api_permission() {
  return array(
    'administer wechat configuration' => array(
      'title' => t('微信接入设置'),
      'description' => t('允许修改微信接入信息.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function wechat_api_menu() {
  $items['admin/config/wechat'] = array(
    'title' => '微信',
    'description' => '微信相关设置.',
    'position' => 'left',
    'weight' => 0,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/wechat/api'] = array(
    'title' => '微信API设置',
    'description' => '设置Token、Appid、Appsecret.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wechat_api_settings_form'),
    'access arguments' => array('administer wechat configuration'),
  );
  $items['wechat'] = array(
    'title' => 'wechat',
    'description' => 'wechat callback',
    'page callback' => 'wechat_api_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function wechat_api_settings_form($form, &$form_state) {
  global $base_url;
  $form['required'] = array(
    '#type' => 'fieldset',
    '#title' => t('Wechat app info'),
    '#description' => t("当前服务器微信接入地址：<b>%base_url</b>", array('%base_url' => $base_url . '/wechat')),
  );


  $form['required']['wechat_api_token'] = array(
    '#type' => 'textfield',
    '#title' => t('Token'),
    '#default_value' => variable_get('wechat_api_token', ''),
    '#required' => TRUE,
  );

  $form['required']['wechat_api_appid'] = array(
    '#type' => 'textfield',
    '#title' => t('Appid'),
    '#default_value' => variable_get('wechat_api_appid', ''),
    '#required' => TRUE,
  );
  $form['required']['wechat_api_appsecret'] = array(
    '#type' => 'textfield',
    '#title' => t('Appsecret'),
    '#default_value' => variable_get('wechat_api_appsecret', ''),
    '#required' => TRUE,
  );
  $form['required']['wechat_api_debug'] = array(
    '#type' => 'checkbox',
    '#title' => t('Debug（测试环境使用）'),
    '#default_value' => variable_get('wechat_api_debug', FALSE),
  );
  $form['#submit'][] = 'wechat_api_access_token_refresh';

  //dpm(variable_get('wechat_api_debug', FALSE));
  return system_settings_form($form);
}

function wechat_api_access_token_refresh($form, &$form_state) {
  libraries_load('wechat');
  $token = $form_state['input']['wechat_api_token'];
  $appid = $form_state['input']['wechat_api_appid'];
  $appsecret = $form_state['input']['wechat_api_appsecret'];
  $options = array(
    'token' => $token,
    'appid' => $appid,
    'appsecret' => $appsecret,
  );
  $wechat = new Wechat($options);
  $access_token = $wechat->checkAuth();
  if (!$access_token) {
    drupal_set_message('参数错误！请检查相关设置。', 'error');
  }
  variable_set("wechat_api_access_token", $access_token);
  variable_set("wechat_api_access_token_time", time());

  //dpm($form_state);
}

function wechat_api_init_wechatobj() {
  $wechat = &drupal_static(__FUNCTION__);
  if (!isset($wechat)) {
    libraries_load('wechat');
    $options = array(
      'token' => variable_get('wechat_api_token', ""),
      'appid' => variable_get('wechat_api_appid', ""),
      'appsecret' => variable_get('wechat_api_appsecret', ""),
    );
    $wechat = new Wechat($options);
    $access_token = variable_get("wechat_api_access_token", '');
    if (variable_get("wechat_api_access_token_time", 0) > time() - 7000 && $access_token != '') {
      $wechat->checkAuth('', '', $access_token);
      $return = $wechat->getServerIp();
      if (!$return) {
        $access_token = $wechat->checkAuth();
        variable_set("wechat_api_access_token", $access_token);
        variable_set("wechat_api_access_token_time", time());
      }
    }
    else {
      $access_token = $wechat->checkAuth();
      variable_set("wechat_api_access_token", $access_token);
      variable_set("wechat_api_access_token_time", time());
    }
  }
  return $wechat;
}

/**
 * 微信接口回调函数，提供验证是否接入成功。在wechat_session模块中使用hook_menu_alter()覆写提供更强大的功能。
 */
function wechat_api_callback() {
  $wechat_obj = wechat_api_init_wechatobj();
  $wechat_obj->valid(variable_get('wechat_api_debug', FALSE));
  $wechat_obj->getRev();
  $xml_obj = $wechat_obj->getRevData();
  $xml_obj = (object) $xml_obj;
  $to_user_name = $wechat_obj->getRevFrom();
  $from_user_name = $wechat_obj->getRevTo();
  $request_time = time();
  $content = format_date(time(), 'short') . '
  api配置成功
  ';
  if ($xml_obj->MsgType == 'text') {
    $content .= $wechat_obj->getRevContent();
  }
  else {
    $content .= 'api配置成功。';
  }

  $return_template = "<xml>
      <ToUserName><![CDATA[%s]]></ToUserName>
      <FromUserName><![CDATA[%s]]></FromUserName>
      <CreateTime>%s</CreateTime>
      <MsgType><![CDATA[text]]></MsgType>
      <Content><![CDATA[%s]]></Content>
      <FuncFlag>0</FuncFlag>
    </xml>";

  $result_str = sprintf($return_template, $to_user_name, $from_user_name, $request_time, $content);

  echo $result_str;


//  //@todo 如果客服模块启用，客服模块优先处理消息
//  $kf_massage = FALSE;
//  if (module_exists('wechat_kf')) {
//    //@todo 客服模块预处理消息，如消息是客服消息返回true。
//    //功能需完善
//    $kf_massage = wechat_kf_process_massage($wechat_obj);
//    if ($kf_massage) {
//      wechat_kf_save_request_messages($wechat_obj);
//    }
//  }
//  //$kf_massage = FALSE;
//  if (!$kf_massage) {
//    //@todo 将消息对象交给“消息管理”模块操作
//    if (module_exists('wechat_messages')) {
//      wechat_messages_save_request_messages($wechat_obj);
//    }
//  }
//  module_invoke_all('wechat_api_callback');
//
//  $array = array();

}

