<?php

/**
 * Implements hook_menu().
 */
function wechat_app_menu() {
  $items['admin/content/wechat-app/add'] = array(
    'title' => '添加新的公众号',
    'description' => '添加新的公众号',
    'page callback' => 'wechat_app_add_form',
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'file' => 'wechat_app.admin.inc',
  );
  $items['admin/content/wechat-app/%wechat_app/edit'] = array(
    'title' => '公众号编辑',
    'description' => '公众号编辑',
    'page callback' => 'wechat_app_edit_form',
    'page arguments' => array(3),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'file' => 'wechat_app.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_entity_info().
 */
function wechat_app_entity_info() {
  $return['wechat_app'] = array(
    'label' => '微信公众号应用',
    'plural label' => '微信公众号应用',
    'description' => '微信公众号应用',
    'entity class' => 'Drupal\wechat_app\Entity\WechatApp',
    'controller class' => 'EntityAPIController',
    'base table' => 'wechat_app',
    'fieldable' => FALSE,
    'access callback' => 'wechat_app_access',
    'uri callback' => 'entity_class_uri',
    'label callback' => 'entity_class_label',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'name'
    ),
    'module' => 'wechat_app',
  );
  return $return;
}

function wechat_app_access($op, $entity, $account, $entity_type) {
  return $account->uid == 1;
}

