<?php

/**
 * Implements hook_menu().
 */
function wechat_app_menu() {
  $items['wechat/%wechat_app'] = array(
    'title' => '微信消息推送地址',
    'page callback' => 'wechat_app_api_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'wechat_app.pages.inc',
  );
  $items['admin/content/application/%application/edit'] = array(
    'title' => '开放平台应用编辑',
    'description' => '开放平台应用编辑',
    'page callback' => 'application_edit_form',
    'page arguments' => array(3),
    'access callback' => 'application_access',
    'access arguments' => array('edit', 3),
    'type' => MENU_LOCAL_TASK,
    'file' => 'application.pages.inc',
  );
  $items['application/%application/notice/callback'] = array(
    'title' => '开放平台通知',
    'description' => '授权事件接收URL',
    'page callback' => 'application_ticket_callback',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_entity_info().
 */
function wechat_app_entity_info() {
  $return['wechat_app'] = array(
    'label' => '微信公众号应用',
    'plural label' => '微信公众号应用',
    'description' => '微信公众号应用',
    'entity class' => 'Drupal\wechat_app\Entity\WechatApp',
    'controller class' => 'EntityAPIController',
    'base table' => 'wechat_app',
    'fieldable' => FALSE,
    'access callback' => 'wechat_app_access',
    'uri callback' => 'entity_class_uri',
    'label callback' => 'entity_class_label',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'name'
    ),
    'module' => 'wechat_app',
  );
  return $return;
}

function wechat_app_access($op, $entity, $account, $entity_type) {
  return $account->uid == 1;
}
