<?php

/**
 * Implements hook_menu().
 */
function wechat_scan_menu() {
  $items['wechat-scan/product/add'] = array(
    'page callback' => 'wechat_scan_product_add_form',
    'access callback' => 'wechat_scan_access',
    'access arguments' => array('product', NULL, 'add'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'wechat_scan.pages.inc',
  );
  $items['wechat-scan/product/%wechat_scan_product/edit'] = array(
    'page callback' => 'wechat_scan_product_edit_form',
    'page arguments' => array(2),
    'access callback' => 'wechat_scan_access',
    'access arguments' => array('product', 2, 'edit'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'wechat_scan.pages.inc',
  );

  $items['admin/structure/wechat_scan_product'] = array(
    'title' => '微信扫一扫设置',
    'description' => '微信用户设置，如：微信登录自动注册为某角色，刷新用户信息等。',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['wechat_scan_settings_form'],
    'access callback' => 'wechat_scan_access',
    'access arguments' => array('product', NULL, 'add'),
    'file' => 'wechat_scan.admin.inc',
  );
  $items['admin/structure/wechat_scan_product/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  return $items;
}

function wechat_scan_product_load($id, $reset = FALSE) {
  $entities = wechat_scan_product_load_multiple(array($id), array(), $reset);
  return reset($entities);
}

function wechat_scan_product_load_multiple($ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('wechat_scan_product', $ids, $conditions, $reset);
}


function wechat_scan_access($type, $entity = NULL, $op = NULL) {
  return TRUE;
}

/**
 * Implements hook_entity_info().
 */
function wechat_scan_entity_info() {
  $return['wechat_scan_product'] = array(
    'label' => t('扫一扫商品信息'),
    'plural label' => t('扫一扫商品信息'),
    'description' => t('扫一扫商品信息.'),
    'entity class' => 'WechatScanProduct',
    'controller class' => 'EntityAPIController',
    'base table' => 'wechat_scan_product',
    'revision table' => 'wechat_scan_product_revision',
    'fieldable' => TRUE,
    'uri callback' => 'entity_class_uri',
    'label callback' => 'entity_class_label',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'title',
      'revision' => 'vid',
    ),
    'bundles' => array(
      'wechat_scan_product' => array(
        'label' => t('扫一扫商品'),
        'admin' => array(
          'path' => 'admin/structure/wechat_scan_product',
          'access arguments' => array('administer users'),
        ),
      ),
    ),
    'module' => 'wechat_scan',
  );
  $return['wechat_scan_product_qrcode'] = array(
    'label' => t('扫一扫商品二维码'),
    'plural label' => t('扫一扫商品二维码'),
    'description' => t('扫一扫商品二维码.'),
    'entity class' => 'WechatScanProductQrcode',
    'controller class' => 'EntityAPIController',
    'base table' => 'wechat_scan_product_qrcode',
    'fieldable' => FALSE,
    'uri callback' => 'entity_class_uri',
    'label callback' => 'entity_class_label',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'title',
    ),
    'module' => 'wechat_scan',
  );


  return $return;
}

class WechatScanProduct extends Entity {
  public $id;
  public $uid;
  public $vid;
  public $title;
  public $created;
  public $changed;

  public $keystandard = 'ean13';
  public $keystr;

  //创建成功返回的PID
  public $pid;

  public $log = '';
  public $is_new_revision;

  function __construct($values = array()) {
    $this->is_new_revision = TRUE;
    parent::__construct($values, 'wechat_scan_product');
  }

  function save() {
    $this->changed = time();

    if (empty($this->created)) {
      $this->created = time();
    }

    if (empty($this->uid)) {
      global $user;
      $this->uid = $user->uid;
    }

    parent::save();
  }
}

class wechat_scan_product_qrcode extends Entity {
  function __construct($values = array()) {
    parent::__construct($values, 'wechat_scan_product_qrcode');
  }

  function save() {
    parent::save();
  }
}