<?php
/**
 * Implements hook_menu().
 */
function wechat_reply_material_menu() {
  $items['reply/test'] = array(
    'title' => '微信回复消息',
    'access arguments' => array('add_all'),
    'description' => 'Add a new property.',
    'page callback' => 'wechat_reply_material_test',
  );

  $items['admin/config/wechat/material-update'] = array(
    'title' => '微信素材同步',
    'description' => '微信素材同步.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wechat_reply_material_update'),
    'access arguments' => array('administer wechat configuration'),
  );

  return $items;

}
use Drupal\wechat_reply_material\NewsMaterial;
use Drupal\wechat_reply_material\FileMaterial;
use Drupal\wechat_reply_material\FileMaterialSave;

function wechat_reply_material_update($form, &$form_state) {
  $form['update'] = array(
    '#type' => 'fieldset',
    '#title' => t('数据同步'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
  );
  $form['update']['type'] = array(
    '#type' => 'select',
    '#title' => t('素材类型'),
    '#options' => array(
      'all' => t('全部'),
      'image' => t('图片'),
      'video' => t('视频'),
      'voice' => t('语音'),
      'news' => t('图文'),
    ),
    '#description' => t('选择素材同步的类型.'),
  );
  $form['update']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('同步'),
  );
  return $form;
}

function wechat_reply_material_update_submit($form, &$form_state) {
  $type = $form_state['values']['update']['type'];
  $wechatObj = wechat_api_init_wechatobj();

  $ForeverCount = $wechatObj->getForeverCount();

  $voice_count = $ForeverCount['voice_count'];
  $video_count = $ForeverCount['video_count'];
  $image_count = $ForeverCount['image_count'];
  $news_count = $ForeverCount['news_count'];

  switch ($type) {
    case 'all': {

      break;
    }
    case 'image': {
      $offset = 0;
      $count = $offset + 20;

      do {
        $imageForeverList = $wechatObj->getForeverList('image', $offset, $count);

        foreach ($imageForeverList['item'] as $image) {
          $fm = new FileMaterial($image);
          $fs = new FileMaterialSave();
          $fm->save($fs);
        }

        $offset = $offset + 20;
        $count = $offset + 20;
      } while ($offset < $image_count);


      break;
    }
    case 'video': {

      break;
    }
    case 'voice': {

      break;
    }
    case 'news': {
      $offset = 0;
      $count = $offset + 20;

      do {
        $imageForeverList = $wechatObj->getForeverList('news', $offset, $count);

        foreach ($imageForeverList['item'] as $item) {
          dpm($item);
          $nm = new NewsMaterial($item);
          $ns = new \Drupal\wechat_reply_material\NewsMaterialSave();
          $nm->save($ns);
//          $fm = new FileMaterial($image);
//          $fs = new FileMaterialSave();
//          $fm->save($fs);
        }

        $offset = $offset + 20;
        $count = $offset + 20;
      } while ($offset < $image_count);
      break;
    }
  }

  $ForeverList = $wechatObj->getForeverList('news', 0, 10);
}

function wechat_reply_material_test() {

//  $wo = wechat_api_init_wechatobj();
//  $a = $wo->getForeverCount();

//  dpm($a);
//  $ForeverList = $wo->getForeverList('news', 0, 10);
//  dpm($ForeverList);

//  foreach ($ForeverList['item'] as $item) {
//    dpm($item);
//    $f = new FileMaterial;
//    $fs = new FileMaterialSave();
//    $f->save($fs);
//    NewsMaterial::save($item);
//  }
  return 'aa';
//  $key = variable_get('wx_pay_client_key', '');
//  $secret = variable_get('wx_pay_client_secret', '');
//  $url = variable_get('wx_pay_client_jspay_api', '');
//  dpm($key);
//  dpm($secret);
//  $key = '39UQNprQSJPZxwfnAKsoaBvPKGmYgG9B';
//  $secret = 'm84hvUMCaYWmXBuKSzqobSCJyPqGtkB3';
//
//  $data = array(
//    'total_fee' => 1,
//    'attach' => 100,
//  );
//
//  $OAuth = new OAuthClient($key, $secret, $url, 'POST', $data);
//  $body = $OAuth->get_body();
//  dpm($body);
//  return 'bbbb';
//  $p = wx_pay_client_get_jspay_url(1, 100);
//  dpm($p);]
//  return 'aaa';
//  https://api.weixin.qq.com/cgi-bin/template/api_set_industry?access_token=ACCESS_TOKEN
  $wo = wechat_api_init_wechatobj();
//  $wo->setTMIndustry(2);
//  "touser":"OPENID",
//   * "template_id":"ngqIpbwh8bUfcSsECmogfXcV14J0tQlEpBO27izEYtY",
//   * "url":"http://www.baidu.com",
//   * "topcolor":"#FF0000",
//   * "data":{
//    * "参数名1": {
//      * "value":"参数",
//   * "color":"#173177"     //参数颜色
//      * },
//   * "Date":{
//      * "value":"06月07日 19时24分",
//   * "color":"#173177"
//      * },
//   * "CardNumber":{
//      * "value":"0426",
//   * "color":"#173177"
//      * },
//   * "Type":{
//      * "value":"消费",
//   * "color":"#173177"
//      * }
  //{{remark.DATA}}
//  $wo->sendTemplateMessage(array(
//    'template_id' => '9r7kUb4JHof9w8xlcgu78nR9p0q36IzcGQBC-VwU6w4',
//    'url' => 'http://weixin.qq.com/download',
//    'touser' => 'oXLV-s_Rwy52YryNW-PU3-OD5la0',
//    'data' => array(
//      'first' => array(
//        'value' => drupal_random_key(5) . '门店申请退款',
//        'color' => '#456789'
//      ),
//      'reason' => array('value' => '换货', 'color' => '#456123'),
//      'refund' => array('value' => '123', 'color' => '#123456'),
//      'remark' => array('value' => "申 请 人：123\n时  间：123456\n点击进入操作\n如有疑问请联系信息部"),
//    ),
//  ));
//  dpm($wo->getForeverCount());
  dpm($wo->getForeverList('news', 0, 10));
//  $wo->tem
  return 'aa';
}

