<?php
/**
 * Implements hook_menu().
 */
function wechat_reply_material_menu() {
  $items['reply/test'] = array(
    'title' => '微信回复消息',
    'access arguments' => array('add_all'),
    'description' => 'Add a new property.',
    'page callback' => 'wechat_reply_material_test',
  );


  return $items;

}

function wechat_reply_material_test() {
//  $key = variable_get('wx_pay_client_key', '');
//  $secret = variable_get('wx_pay_client_secret', '');
//  $url = variable_get('wx_pay_client_jspay_api', '');
//  dpm($key);
//  dpm($secret);
//  $key = '39UQNprQSJPZxwfnAKsoaBvPKGmYgG9B';
//  $secret = 'm84hvUMCaYWmXBuKSzqobSCJyPqGtkB3';
//
//  $data = array(
//    'total_fee' => 1,
//    'attach' => 100,
//  );
//
//  $OAuth = new OAuthClient($key, $secret, $url, 'POST', $data);
//  $body = $OAuth->get_body();
//  dpm($body);
//  return 'bbbb';
  $p = wx_pay_client_get_jspay_url(1, 100);
  dpm($p);
  return 'aaa';
  $wo = wechat_api_init_wechatobj();
  dpm($wo->getForeverCount());
  dpm($wo->getForeverList('news', 0, 10));
  return 'aa';
}

class ReplayNews {

}