<?php
define('USERBINDFIELDNAME', 'user_bind_user_referenced');
include_once 'user_bind.features.inc';
/**
 * Implements hook_menu().
 */
function user_bind_menu() {
  //用户的微信信息
  $items['user/%user/wechat-info'] = array(
    'title' => '微信绑定',
    'page callback' => 'user_bind_wechat_info',
    'page arguments' => array(1),
    'access callback' => 'user_view_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/config/wechat/user-bind'] = array(
    'title' => '微信绑定设置',
    'description' => '微信绑定设置.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_bind_settings_form'),
    'access arguments' => array('administer user bind configuration'),
  );

  $items['user/wechat-user-bind'] = array(
    'title' => '微信绑定',
    'page callback' => 'user_bind_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function user_bind_page() {
  $output = '';
  global $user;
  if ($user->uid) {
    drupal_goto('user/' . $user->uid . '/wechat-info');
  }
  else {
    $link = l(t('登录'), 'user/login', array(
      'query' => array(
        'destination' => 'user/wechat-user-bind'
      ),
    ));
    $output .= "<div>请先{$link}！</div>";
    return $output;
  }
}

function user_bind_wechat_info($user) {
  $output = '';
  $wechat_user = WechatUser::loadByUid($user->uid);

  if (empty($wechat_user)) {
    $form = drupal_get_form('user_bind_form', $user);
    $output .= render($form);
    return $output;
  }
  return '已绑定微信！';
}

function user_bind_form($form, &$form_state, $user) {
  $form_state['user'] = $user;

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('点击绑定')
  );
  $form['actions']['qr'] = array(
    '#type' => 'container',
    '#prefix' => '<div id="qr-bind-wrapper">',
    '#suffix' => '</div>',
  );
  $form['actions']['qr']['img'] = array(
    '#type' => 'item',
    '#title' => t(''),
  );
  $form['actions']['qr']['bind'] = array(
    '#type' => 'button',
    '#value' => t('二维码绑定'),
    '#ajax' => array(
      'callback' => 'user_bind_qr_bind_callback',
      'wrapper' => 'qr-bind-wrapper',
    ),
    '#markup' => '<div>asdfjiasdnfklasdfjkl</div>',

  );
  return $form;
}

function user_bind_qr_bind_callback($form, &$form_state) {
  global $user;
  $wechatQr2 = new WechatQr2();
  $wechatQr2->title = '绑定码自动生成->' . format_date(time(), 'short');
  $wechatQr2->uid = $user->uid;
  $wechatQr2->type = 'user_bind_qr';
  $wechatQr2->qr_type = 0;
  $wechatQr2->expire = 300;
  $wechatQr2->save();
  $wechatQr2_w = $wechatQr2->wrapper();
  $wechatQr2_w->{USERBINDFIELDNAME}->set($user);
  $wechatQr2_w->save();
  $form['actions']['qr']['img']['#markup'] = '<div>' . $wechatQr2->getUrl() . '</div>';
  return $form['actions']['qr'];
}

function user_bind_form_submit($form, &$form_state) {
  drupal_goto('wechat/user/login', array(
    'query' => array(
      'goto' => 'user/' . $form_state['user']->uid,
      'error' => 'node',
      'state' => 'update',
      'type' => 'snsapi_base',
    )
  ));
}
