<?php

class JSSDK {
  private $appId;
  private $appSecret;

  public function __construct($appId = NULL, $appSecret = NULL) {
    $this->appId = !empty($appId) ? $appId : variable_get('wechat_api_appid', '');
    $this->appSecret = !empty($appSecret) ? $appSecret : variable_get('wechat_api_appsecret', '');
  }

  public function getSignPackage() {
    $jsapiTicket = $this->getJsApiTicket();

    // 注意 URL 一定要动态获取，不能 hardcode.
    $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443) ? "https://" : "http://";
    $url = "$protocol$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";

    $timestamp = time();
    $nonceStr = $this->createNonceStr();

    // 这里参数的顺序要按照 key 值 ASCII 码升序排序
    $string = "jsapi_ticket=$jsapiTicket&noncestr=$nonceStr&timestamp=$timestamp&url=$url";

    $signature = sha1($string);

    $signPackage = array(
      "appId" => $this->appId,
      "nonceStr" => $nonceStr,
      "timestamp" => $timestamp,
      "url" => $url,
      "signature" => $signature,
      "rawString" => $string
    );
    return $signPackage;
  }

  private function createNonceStr($length = 16) {
    $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    $str = "";
    for ($i = 0; $i < $length; $i++) {
      $str .= substr($chars, mt_rand(0, strlen($chars) - 1), 1);
    }
    return $str;
  }

  private function getJsApiTicket() {

    $data = json_decode(variable_get('jssdk_jsapi_ticket', '{"expire_time":0}'));

    if ($data->expire_time < time()) {
      $accessToken = $this->getAccessToken();
      // 如果是企业号用以下 URL 获取 ticket
      // $url = "https://qyapi.weixin.qq.com/cgi-bin/get_jsapi_ticket?access_token=$accessToken";
      $url = "https://api.weixin.qq.com/cgi-bin/ticket/getticket?type=jsapi&access_token=$accessToken";
      $res = json_decode($this->httpGet($url));
      $ticket = $res->ticket;

      if ($ticket) {
        $data->expire_time = time() + 7000;
        $data->jsapi_ticket = $ticket;
        variable_set('jssdk_jsapi_ticket', json_encode($data));
      }
    }
    else {
      $ticket = $data->jsapi_ticket;
    }

    return $ticket;
  }

  private function ToUrlParams($urlObj) {
    $buff = "";
    foreach ($urlObj as $k => $v) {
      if ($k != "sign") {
        $buff .= $k . "=" . $v . "&";
      }
    }
    $buff = trim($buff, "&");
    return $buff;
  }

  /**
   *
   * 获取地址js参数
   *
   * @return 获取共享收货地址js函数需要的参数，json格式可以直接做参数使用
   */
  public function GetEditAddressParameters() {

    $data = array();

    $data["appid"] = variable_get('wechat_api_appid', '');
    $data["url"] = "http://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
    $time = time();
    $data["timestamp"] = "$time";
    $data["noncestr"] = drupal_random_key(10);
    $data["accesstoken"] = $this->getAccessToken();

    ksort($data);
    $params = $this->ToUrlParams($data);
    $addrSign = sha1($params);

    $afterData = array(
      "addrSign" => $addrSign,
      "appId" => $data["appid"],
      "timeStamp" => $data["timestamp"],
      "nonceStr" => $data["noncestr"]
    );
    $parameters = $afterData;
    return $parameters;
  }

  private function getAccessToken() {
    $wechat_obj = wechat_api_init_wechatobj();
    $access_token = $wechat_obj->get_access_token();
    return $access_token;
  }

  private function httpGet($url) {
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
    curl_setopt($curl, CURLOPT_TIMEOUT, 500);
    curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, FALSE);
    curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, FALSE);
    curl_setopt($curl, CURLOPT_URL, $url);

    $res = curl_exec($curl);
    curl_close($curl);

    return $res;
  }
}

/**
 * Implements hook_page_build().
 */
function wechat_jssdk_page_build(&$page) {
  $JSSDK = new JSSDK();
  $getSignPackage = $JSSDK->getSignPackage();

  $settings = array(
    'appId' => $getSignPackage['appId'],
    'timestamp' => $getSignPackage['timestamp'],
    'nonceStr' => $getSignPackage['nonceStr'],
    'signature' => $getSignPackage['signature'],
    'editAddress' => $JSSDK->GetEditAddressParameters(),
  );

//  $OAuth = new OAuthClient('CfRGN558nrHrgCTPFj8fGZDNUDPZjRiS', 'qCotH45C4XKhkbwq2UPbP7npVAKAcHYh', 'http://api.ugreat.net/services/wx-pay-services/get-address-parameter.json', 'POST', array());
//  $body = $OAuth->get_body();
//  $data = $body->data;
//  $data = json_decode($data);
//  $data = (array) $data;
//
////  $editAddressData = $JSSDK->GetEditAddressParameters();
//  $editAddress = array(
//    "addrSign" => $data['addrSign'],
//    "appId" => $data['appId'],
//    "timeStamp" => $data['timeStamp'],
//    "nonceStr" => $data['nonceStr'],
//  );
//  drupal_add_js(array('editAddress' => $editAddress), 'setting');

  drupal_add_js(array('wechatJSSDK' => $settings), 'setting');

  drupal_add_js(drupal_get_path('module', 'wechat_jssdk') . "/lib/jweixin-1.0.0.js");
  drupal_add_js(drupal_get_path('module', 'wechat_jssdk') . "/wechat_jssdk.js");
}