<?php
define('WUUPRE', 'wx_');
/**
 * Implements hook_views_api().
 */
function wechat_user_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_menu().
 */
function wechat_user_menu() {
  //认证路径
  $items['wechat/auth'] = array(
    'title' => 'Wechat Login',
    'page callback' => 'wechat_user_auth',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  //自定义登录回调
  $items['wechat/user/login'] = array(
    'title' => 'Wechat Login',
    'page callback' => 'wechat_user_login_two',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['admin/structure/wechat_user'] = array(
    'title' => '微信用户设置',
    'description' => '微信用户设置，如：微信登录自动注册为某角色，刷新用户信息等。',
    'page callback' => 'wechat_user_settings_page',
    'access callback' => 'user_access',
    'access arguments' => array('wechat user update user info'),
    //'file' => 'wechat_user.forms.inc',
  );

  $items['admin/structure/wechat_user/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['admin/wechat/user/%wechat_user/edit'] = array(
    'title' => '编辑用户资料',
    'description' => '微信用户设置，如：微信登录自动注册为某角色，刷新用户信息等。',
    'page callback' => 'wechat_user_edit_form',
    'page arguments' => array(3),
    'access arguments' => array('wechat user update user info'),
    'weight' => -10,
    'file' => 'wechat_user.forms.inc',
  );

  return $items;
}

function wechat_user_create_login_url($goto, $error = 'node') {
  return "/wechat/user/login?goto={$goto}&error={$error}&state=1&type=snsapi_base";
}

function wechat_user_edit_access($current_user) {
  global $user;
  if ($user->uid == $current_user->uid) {
    return TRUE;
  }
  if (user_access('admin')) {
    return TRUE;
  }

  return FALSE;
}


function wechat_user_settings_page() {
  $output = '';
  $form = drupal_get_form('wechat_user_op_user');
  $output .= render($form);
  return $output;
}


function wechat_user_op_user($form, &$form_state) {
  $form['group'] = array(
    '#type' => 'fieldset',
    '#title' => t('分组管理'),
    '#weight' => 3,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#tree' => TRUE,
  );
  $form['group']['update_group'] = array(
    '#type' => 'submit',
    '#submit' => array('wechat_user_group_update_group'),
    '#value' => t('同步分组数据'),
  );

  $form['openid'] = array(
    '#type' => 'fieldset',
    '#title' => t('更新单个用户信息'),
    '#weight' => 3,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#tree' => TRUE,
  );
  $form['openid']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('微信用户OpenId'),
    '#size' => 60,
    '#maxlength' => 128,
    '#description' => t('填写需要更新的微信用户OpenId，不填写则更新所有微信用户.'),
  );
  $form['openid']['update_user_info'] = array(
    '#type' => 'submit',
    '#submit' => array('wechat_user_openid_update_user_info'),
    '#value' => t('更新用户信息'),
  );

  $form['update'] = array(
    '#type' => 'fieldset',
    '#title' => t('同步当前站点用户信息'),
    '#weight' => 3,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#tree' => TRUE,
  );
  $form['update']['update_user_info'] = array(
    '#type' => 'submit',
    '#submit' => array('wechat_user_update_update_user_info'),
    '#value' => t('同步当前站点用户信息'),
  );

  $form['pull'] = array(
    '#type' => 'fieldset',
    '#title' => t('同步所有用户信息'),
    '#weight' => 3,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#tree' => TRUE,
  );
  $form['pull']['pull_user_info'] = array(
    '#type' => 'submit',
    '#submit' => array('wechat_user_pull_pull_user_info'),
    '#value' => t('同步所有用户信息'),
  );
  return $form;
}

function wechat_user_group_update_group($form, &$form_state) {
  $wechatObj = wechat_api_init_wechatobj();
  $groups = $wechatObj->getGroup();
  foreach ($groups['groups'] as $group) {
    $values = array();
    $values['gid'] = $group['id'];
    $values['name'] = $group['name'];
    $values['count'] = $group['count'];
    $groupObj = new WechatUserGroup($values);
    $groupObj->save();
  }
  dpm($groups);
}

function wechat_user_openid_update_user_info($form, &$form_state) {
  $openid = $form_state['values']['openid']['value'];
  if (!empty($openid)) {
    wechat_user_registry_user($openid);
  }
}


function wechat_user_pull_pull_user_info($form, &$form_state) {

  $wechat_obj = wechat_api_init_wechatobj();
  $user_list = $wechat_obj->getUserList();
  $openid_list = $user_list['data']['openid'];

  //后期改为批处理操作防止超时。
  //wechat_user_user_registry($openid_list);
  $operations = array();
  foreach ($openid_list as $openid) {
    $operations[] = array(
      'wechat_user_registry_user',
      array($openid)
    );
  }


  batch_set(array(
    'operations' => $operations,
    'title' => t('微信用户信息更新'),
  ));

}

function wechat_user_update_update_user_info($form, &$form_state) {
  $entities = wechat_user_load_multiple(FALSE);
  $operations = array();
  foreach ($entities as $entity) {
    $operations[] = array(
      'wechat_user_registry_user',
      array($entity->openid)
    );
  }
  batch_set(array(
    'operations' => $operations,
    'title' => t('更新当前站点的微信用户信息'),
  ));
}

function wechat_user_login_two() {

  $goto = $_GET['goto'];
  $error = $_GET['error'];
  $state = $_GET['state'];
  $type = $_GET['type'];

  $we_obj = wechat_api_init_wechatobj();
  $auth_url = $we_obj->getOauthRedirect(url('wechat/auth', array(
    'absolute' => TRUE,
    'query' => array('destination' => $goto, 'error' => $error)
  )), $state, $type);
  drupal_goto($auth_url);
}

function wechat_user_user_registry($openid_list) {
  foreach ($openid_list as $user_open_id) {
    wechat_user_registry_user($user_open_id);
  }
}

/**
 * @param $user_open_id
 * @return bool|mixed|\stdClass
 * @throws \Exception
 * 注册用户，没有关注不注册
 */
function wechat_user_registry_user($user_open_id) {
  $wechat_obj = wechat_api_init_wechatobj();
  $user_info = $wechat_obj->getUserInfo($user_open_id);
  if ($user_info['subscribe']) {//判断是否关注
    $user_name = 'wx_' . $user_open_id;
    $user = user_load_by_name($user_name);
    if (!$user) {//不存在则创建
      $wechat_user_entity = entity_create('wechat_user', array());
      // auto register
      $user_name = WUUPRE . $user_open_id;
      $new_user = array(
        'name' => $user_name,
        'pass' => user_password(),
        'status' => 1,
      );
      $account = user_save(NULL, $new_user);
    }
    else {//存在则更新
      $account = $user;
      $wechat_user_entity = WechatUser::loadByUid($user->uid);
    }
    $wechat_user_entity->uid = $account->uid;
    foreach ($user_info as $key => $value) {
      $wechat_user_entity->{$key} = $value;
    }
    $wechat_user_entity->save();
    return $account;
  }
  return FALSE;
}

/**
 * Implements hook_token_info_alter().
 */
function wechat_user_token_info_alter(&$data) {
  $data['tokens']['user']['wechat_user_nickname'] = array(
    'name' => '用户绑定的微信的昵称',
    'description' => '用户绑定的微信的昵称'
  );
}

/**
 * Implements hook_tokens().
 */
function wechat_user_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  if ($type == 'user' && !empty($data['user'])) {
    $account = $data['user'];
    foreach ($tokens as $name => $original) {
      switch ($name) {
        // Basic user account information.
        case 'wechat_user_nickname':
          // In the case of hook user_presave uid is not set yet.
          $wechat_user_entity = WechatUser::loadByUid($account->uid);
          $nickname = $wechat_user_entity->nickname;
          $replacements[$original] = !empty($nickname) ? utf8_decode($nickname) : $account->name;
          break;
      }
    }
  }
  return $replacements;
}

/**
 * Implements hook_entity_info().
 */
function wechat_user_entity_info() {
  $return['wechat_user'] = array(
    'label' => t('Wechat user'),
    'plural label' => t('Wechat users'),
    'description' => t('Wechat users.'),
    'entity class' => 'WechatUser',
    'controller class' => 'EntityAPIController',
    'views controller class' => 'WechatUserViewsController',
    'base table' => 'wechat_user',
    'fieldable' => TRUE,
    'uri callback' => 'entity_class_uri',
    'label callback' => 'entity_class_label',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'nickname'
    ),
    'access callback' => 'wechat_user_access',
    'module' => 'wechat_user',
    'metadata controller class' => 'WechatUserMetadataController',
    'bundles' => array(
      'wechat_user' => array(
        'label' => t('Wechat user'),
        'admin' => array(
          'path' => 'admin/structure/wechat_user',
          'access arguments' => array('administer users'),
        ),
      ),
    ),
    'view modes' => array(
      'full' => array(
        'label' => t('User account'),
        'custom settings' => FALSE,
      ),
    ),
  );
  $return['wechat_user_group'] = array(
    'label' => t('微信用户分组'),
    'plural label' => t('微信用户分组'),
    'description' => t('微信用户分组.'),
    'entity class' => 'WechatUserGroup',
    'controller class' => 'EntityAPIController',
    'base table' => 'wechat_user_group',
    'fieldable' => FALSE,
    'entity keys' => array(
      'id' => 'id',
      'label' => 'name'
    ),
    'module' => 'wechat_user',
  );

  return $return;
}

function wechat_user_load($id, $reset = FALSE) {
  $entities = wechat_user_load_multiple(array($id), array(), $reset);
  return reset($entities);
}

function wechat_user_load_multiple($ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('wechat_user', $ids, $conditions, $reset);
}

function wechat_user_group_load($id, $reset = FALSE) {
  $entities = wechat_user_load_multiple(array($id), array(), $reset);
  return reset($entities);
}

function wechat_user_group_load_multiple($ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('wechat_user_group', $ids, $conditions, $reset);
}

function wechat_user_load_by_openid($openid) {
  $entities = wechat_user_load_multiple(FALSE, array('openid' => $openid));
  return reset($entities);
}

function wechat_user_access($op, $wechat_user = NULL, $account = NULL) {
  if (user_access('administer wechat user', $account)) {
    return TRUE;
  }
  return TRUE;
}

/**
 * Implements hook_permission().
 */
function wechat_user_permission() {
  return array(
    'wechat user update user info' => array(
      'title' => t('更新微信用户信息'),
      'description' => t('更新微信用户信息.'),
    ),
  );
}

function wechat_user_get_wechat_user_by_openid($openid) {
  $wechat_user = wechat_user_load_multiple(FALSE, array('openid' => $openid));
  if (!empty($wechat_user)) {
    return reset($wechat_user);
  }
  return FALSE;
}

function wechat_user_get_user_by_openid($openid) {
  $wechat_user = wechat_user_load_multiple(FALSE, array('openid' => $openid));
  if (!empty($wechat_user)) {
    $wechat_user = reset($wechat_user);
    return user_load($wechat_user->uid);
  }
  return FALSE;
}

function _wechat_user_login($uid) {
  global $user;
  $user = user_load($uid);
  drupal_session_regenerate();
}

function wechat_user_auth() {
  $wechat_obj = wechat_api_init_wechatobj();
  $state = isset($_GET['state']) ? $_GET['state'] : 0;
  $error = isset($_GET['error']) ? $_GET['error'] : '';
  $destination = isset($_GET['destination']) ? $_GET['destination'] : '';
  $code = isset($_GET['code']) ? $_GET['code'] : '';

  // error
  if ((!$state) || (!$code)) { // error
    drupal_goto($error);
  }

  $access_data = $wechat_obj->getOauthAccessToken();

  if (empty($access_data)) {
    drupal_goto($error);
  }

  // check if already connectted
  if ($current_user = wechat_user_get_user_by_openid($access_data['openid'])) {
    _wechat_user_login($current_user->uid);
    // todo update user info
    if (empty($destination)) {
      $destination = 'user/' . $current_user->uid;
    }
    drupal_goto($destination);
  }

  $account = wechat_user_registry_user($access_data['openid']);
  if (!empty($account)) {
    _wechat_user_login($account->uid);
    drupal_goto($destination);
  }
  drupal_goto($error);
}

class WechatUserGroup extends Entity {
  public $id;
  public $gid;
  public $name;
  public $count;

  public function __construct($values = array()) {
    parent::__construct($values, 'wechat_user_group');
  }

  function  loadByGid($gid) {
    $entities = wechat_user_group_load_multiple(FALSE, array('gid' => $gid));
    if (!empty($entities)) {
      return reset($entities);
    }
    return $this;
  }

  static function  exists($gid) {
    $entities = wechat_user_group_load_multiple(FALSE, array('gid' => $gid));
    if (!empty($entities)) {
      return reset($entities);
    }
    return FALSE;
  }

  function save() {
    $entity = $this->loadByGid($this->gid);
    $this->id = $entity->id;
    parent::save();
  }
}

class WechatUser extends Entity {
  public $id;
  public $uid;

  public $subscribe;
  public $openid;
  public $nickname;
  public $sex;
  public $city;
  public $country;
  public $province;
  public $language;
  public $headimgurl;
  public $subscribe_time;
  public $unionid;
  public $remark;
  public $groupid;

  public function  nickname() {
    return utf8_decode($this->nickname);
  }

  /**
   * @param $uid
   * @return static
   * 通过UID调取WechatUser
   */
  static function loadByUid($uid) {
    $wechat = wechat_user_load_multiple(FALSE, array('uid' => $uid));
    if (empty($wechat)) {
      return new static(array('uid' => $uid));
    }
    return reset($wechat);
  }

  public function  openid() {
    return $this->openid;
  }

  public function __construct($values = array()) {
    parent::__construct($values, 'wechat_user');
  }

  protected function defaultLabel() {
    return utf8_decode($this->nickname);
  }

  public function save() {
    $this->nickname = utf8_encode($this->nickname);
    if ($group = WechatUserGroup::exists($this->groupid)) {
      $this->groupid = $group->id;
    }
    parent::save();
  }
}

class WechatUserMetadataController extends EntityDefaultMetadataController {

  public function entityPropertyInfo() {
    $info = parent::entityPropertyInfo();
    $properties = &$info[$this->type]['properties'];

    $properties['groupid'] = array(
      'type' => 'wechat_user_group',
      'label' => t('用户分组'),
      'description' => t('关联用户分组信息.'),
      'getter callback' => 'entity_property_getter_method',
      'setter callback' => 'entity_property_setter_method',
      'setter permission' => 'administer wechat user',
      'schema field' => 'groupid',
    );

    $properties['headimgurl'] = array(
      'type' => 'text',
      'label' => t('headimgurl'),
      'description' => t('headimgurl of wechat user.'),
      'getter callback' => 'entity_property_verbatim_get',
      'setter callback' => 'entity_property_verbatim_set',
      'setter permission' => 'administer wechat user',
      'schema field' => 'headimgurl',
    );

    $properties['subscribe_time'] = array(
      'type' => 'date',
      'label' => t('Subscribe time'),
      'description' => t('Subscribe time of wechat user.'),
      'setter callback' => 'entity_property_verbatim_set',
      'setter permission' => 'administer wechat user',
      'schema field' => 'subscribe_time',
      'required' => TRUE,
    );

    return $info;
  }
}

class WechatUserViewsController extends EntityDefaultViewsController {
  public function views_data() {
    $data = parent::views_data();
    $data['wechat_user']['nickname']['field']['handler'] = 'views_handler_field_nickname';
    return $data;
  }
}

class views_handler_field_nickname extends views_handler_field {
  public function  render($values) {
    return utf8_decode($values->wechat_user_nickname);
  }
}
