<?php
/**
 * Created by PhpStorm.
 * User: sosyuki
 * Date: 2016/9/1
 * Time: 13:34
 */

namespace Drupal\wechat_app\Entity;


class WechatApp extends \Entity {

  public $id;
  public $name;
  public $status = 1;

  public $subscription;
  public $appid;
  public $appsecret;
  public $token;
  public $aes_key;

  public $access_token;

  public $uid;
  public $created;
  public $changed;


  public $wechat;

  public function __construct(array $values = array()) {
    parent::__construct($values, 'wechat_app');
  }

  public function save() {


    $this->changed = time();
    if (empty($this->created)) {
      $this->created = time();
    }
    if (empty($this->uid)) {
      global $user;
      $this->uid = $user->uid;
    }

    return parent::save(); // TODO: Change the autogenerated stub
  }

}